### ISSUE TITLE
Not able to run network latency experiments with cri-o

### ISSUE THREAD

**Issue by ivanape** [litmuschaos/chaos-operator#390]
**What happened**:

When I try to execution network latency experiment I got following error:

**MountVolume.SetUp failed for volume "cri-socket" : hostPath type check failed: /var/run/crio/crio.sock is not a file**

![image](https://user-images.githubusercontent.com/3056856/133609838-8b94bcdf-cfcb-4c12-bfcc-4ff0c13fb7e6.png)

**What you expected to happen**:

Apply latency.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a minikube instance with:

`minikube start --cpus 4 --memory 4g --container-runtime=cri-o --driver virtualbox`

2. Deploy litmus:

`kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-v1.13.8.yaml`

3. Apply  RABC

`kubectl apply -f chaos-rabc.yml -n default`

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-network-latency-sa
  namespace: default
  labels:
    name: pod-network-latency-sa
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-network-latency-sa
  namespace: default
  labels:
    name: pod-network-latency-sa
    app.kubernetes.io/part-of: litmus
rules:
- apiGroups: [""]
  resources: ["pods","events"]
  verbs: ["create","list","get","patch","update","delete","deletecollection"]
- apiGroups: [""]
  resources: ["pods/exec","pods/log","replicationcontrollers"]
  verbs: ["create","list","get"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","list","get","delete","deletecollection"]
- apiGroups: ["apps"]
  resources: ["deployments","statefulsets","daemonsets","replicasets"]
  verbs: ["list","get"]
- apiGroups: ["apps.openshift.io"]
  resources: ["deploymentconfigs"]
  verbs: ["list","get"]
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["list","get"]
- apiGroups: ["litmuschaos.io"]
  resources: ["chaosengines","chaosexperiments","chaosresults"]
  verbs: ["create","list","get","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-network-latency-sa
  namespace: default
  labels:
    name: pod-network-latency-sa
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-network-latency-sa
subjects:
- kind: ServiceAccount
  name: pod-network-latency-sa
  namespace: default
```

4. Apply Chaos Experiment

`kubectl apply -f chaos-experiment.yml -n default`

```
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Network latency
kind: ChaosExperiment
metadata:
  name: pod-network-latency
  labels:
    app.kubernetes.io/component: demo
    name: pod-network-latency
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "apps"
          - "batch"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "pods"
          - "pods/log"
          - "pods/exec"
          - "events"
          - "configmaps"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
      - apiGroups:
          - ""
        resources:
          - endpoints
          - services
        verbs:
          - get
          - list
          - watch
    image: 'litmuschaos/go-runner:1.13.8'
    imagePullPolicy: Always
    hostPID: true
    securityContext:
      containerSecurityContext:
        privileged: true
        capabilities:
          add: ["NET_ADMIN"]
    args:
    - -c
    - ./network-latency
    command:
    - /bin/bash
    env:
    - name: APP_NAMESPACE
      value: ''
    - name: APP_LABEL
      value: ''
    - name: CHAOSENGINE
      value: ''
    - name: CHAOS_NAMESPACE
      value: ''
    - name: LATENCY_NAMESPACE
      value: ''
    - name: LATENCY_LABEL
      value: ''
    - name: ANSIBLE_STDOUT_CALLBACK
      value: 'default'
    - name: TOTAL_CHAOS_DURATION
      value: ''
    - name: LIB
      value: 'litmus'
    - name: RAMP_TIME
      value: ''
    - name: APP_LABEL
      value: ''
    - name: LATENCY_PORT
      value: ''
    - name: LATENCY
      value: ''
    - name: JITTER
      value: ''
    - name: CHAOS_NODE
      value: ''
    labels:
      role: logs
      experiment: network-latency
      app.kubernetes.io/component: demo
    hostFileVolumes:
    - name: cri-socket
      mountPath: /var/run/crio/crio.sock
      nodePath: /var/run/crio/crio.sock
      type: Socket
    - name: cri-yaml
      mountPath: /etc/crictl.yaml 
      nodePath: /etc/crictl.yaml 
```
If we check now the experiment deployed we can see that the node **type: Socket** is missing:

![image](https://user-images.githubusercontent.com/3056856/133609465-4c51acb8-59fa-4d5b-a8bf-ea4ca88a4a70.png)

5. Create a demo deployment:

`kubectl create deployment nginx --image nginx -n default`

6. Apply the Chaos Engine:

`kubectl apply -f chaos-engine.yml -n default`

```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-network-chaos
  namespace: default
spec: 
  # It can be active/stop
  engineState: 'active'
  appinfo: 
    appns: 'default'
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: 'app=nginx'
    appkind: 'deployment'
  chaosServiceAccount: pod-network-latency-sa
  experiments:
    - name: pod-network-latency
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '60' # in seconds

            - name: NETWORK_LATENCY
              value: '2000'
```

**Anything else we need to know?**:

I have tested following YAML for deploying a Pod and I can mount with no error `crio.sock` file.

```
apiVersion: v1
kind: Pod
metadata:
  name: myapp4
  labels:
    name: myapp4
spec:
  containers:
  - name: myapp4
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "sleep 5000"]     
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /var/run/crio/crio.sock
        name: crio-sock
  volumes:
    - name: crio-sock
      hostPath:
        path: /var/run/crio/crio.sock
        type: Socket
```

Thank you so much for your help!

**Comment by Jonsy13** [comment]
Hi @ivanape ,By default the container-runtime is taken as docker. For cri-o, you have to provide "crio" as value for ENV CONTAINER_RUNTIME in the experiment tunables in ChaosEngine.
Refer:  https://v1-docs.litmuschaos.io/docs/pod-network-latency/#prepare-chaosengine
Let us know, if the issue still persists.

**Comment by ivanape** [comment]
Thank you @prithvi1307 , @Jonsy13 for your help!

I have tested with following YAML, but I got the same error :(.

```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-network-chaos
  namespace: default
spec: 
  # It can be active/stop
  engineState: 'active'
  appinfo: 
    appns: 'default'
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: 'app=nginx'
    appkind: 'deployment'
  chaosServiceAccount: pod-network-latency-sa
  experiments:
    - name: pod-network-latency
      spec:
        components:
          env:
            - name: CONTAINER_RUNTIME
              value: crio

            - name: SOCKET_PATH
              value: /var/run/crio/crio.sock

            - name: TOTAL_CHAOS_DURATION
              value: '60' # in seconds

            - name: NETWORK_LATENCY
              value: '2000'
```

Thank you!
